/* ==========================================================================
   THE PAGES SHOWN ON THE FRONT DOOR, BUILT FROM A REAL EXPORT.

       npx tsx scripts/make-showcase-pages.ts ~/Downloads/files.zip

   The zip is what PageFly hands over when a whole set is exported page by page:
   one `<Name>.pagefly` and one `<Name>-preview.html` per page, paired by name.

   WHY A SCRIPT AND NOT A COPY COMMAND. These assets are refreshed whenever the
   demo store is rebuilt, and the refresh has steps that are each easy to get
   subtly wrong by hand: pairing the two files, slugging the names so the
   manifest and the files agree, and making the HTML light enough to sit in a
   hero. Done by hand once, the next person does it differently and the rail
   half-breaks.

   THE LAZY IMAGES ARE THE WHOLE REASON THIS IS NOT `cp`. A set of previews
   carries well over a hundred external images, every one full size — one home
   page alone had 78. Seven thumbnails in a hero would pull all of them before a
   visitor had read the headline. `loading="lazy"` costs nothing, changes
   nothing about what renders, and means a thumbnail — which only ever shows the
   top of a tall page — fetches the handful actually in that first screen.

   IT WRITES INTO AN EMPTY DIRECTORY. The previous set is removed first, so a
   page dropped from the export does not linger as a file the manifest no longer
   names and nothing ever serves.
   ========================================================================== */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { unzipSync, strFromU8 } from "fflate";

const OUT = join(import.meta.dirname, "..", "public", "showcase", "pages");

/**
 * `HollisRowe-Private-Sale-preview.html` → `private-sale`.
 *
 * The store's own name is dropped: it is the same on every entry, so repeating
 * it in seven file names says nothing and makes the manifest read as a list of
 * one thing. What is left is the page, which is what everything downstream is
 * keyed by.
 */
function slugOf(entry: string, brand: string): string {
  return entry
    .replace(/\.(pagefly|html)$/i, "")
    .replace(/-preview$/i, "")
    .replace(new RegExp(`^${brand}[-_]?`, "i"), "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/** The prefix every entry shares, so it can be stripped. */
function brandOf(names: string[]): string {
  const first = names[0]?.split("-")[0] ?? "";
  return names.every((n) => n.startsWith(first)) ? first : "";
}

/**
 * Every `<img>` made lazy, and nothing else touched.
 *
 * A REGEX OVER HTML, WHICH IS USUALLY WRONG. It is right here for one reason:
 * the input is machine-generated by one exporter, `<img` is always followed by
 * attributes and closed with `>`, and the edit inserts an attribute rather than
 * restructuring anything. A parser would be a dependency and a second thing to
 * keep correct. The count below is what makes it safe — if the shape of the
 * export ever changes, it comes back zero and the script stops.
 */
function lazify(html: string): { out: string; changed: number } {
  let changed = 0;
  const out = html.replace(/<img\b(?![^>]*\bloading=)/gi, () => {
    changed++;
    return `<img loading="lazy" decoding="async"`;
  });
  return { out, changed };
}

function main(): void {
  const [zipPath] = process.argv.slice(2);
  if (!zipPath) {
    console.error("usage: make-showcase-pages.ts <export.zip>");
    process.exitCode = 1;
    return;
  }

  const files = unzipSync(readFileSync(zipPath));
  const names = Object.keys(files).filter((n) => !n.startsWith("__MACOSX"));
  const brand = brandOf(names);

  /* Paired by slug rather than by position: a zip's key order is not
     guaranteed, and a set where the HTML and the .pagefly came out in different
     orders would put one page's file behind another page's picture. */
  const pages = new Map<string, { html?: string; pagefly?: string }>();
  for (const name of names) {
    const slug = slugOf(name, brand);
    const hit = pages.get(slug) ?? {};
    if (/\.html$/i.test(name)) hit.html = name;
    if (/\.pagefly$/i.test(name)) hit.pagefly = name;
    pages.set(slug, hit);
  }

  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  const written: string[] = [];
  for (const [slug, pair] of pages) {
    if (!pair.html || !pair.pagefly) {
      throw new Error(
        `"${slug}" has only ${pair.html ? "an .html" : "a .pagefly"} — every page needs both`,
      );
    }

    const { out, changed } = lazify(strFromU8(files[pair.html]));
    if (changed === 0)
      throw new Error(`${pair.html} has no <img> to make lazy — has the export changed shape?`);

    writeFileSync(join(OUT, `${slug}.html`), out);
    writeFileSync(join(OUT, `${slug}.pagefly`), files[pair.pagefly]);
    written.push(slug);

    console.log(
      `  ${slug.padEnd(16)} html ${String(Math.round(out.length / 1024)).padStart(4)}KB ` +
        `(${String(changed).padStart(3)} images made lazy)   ` +
        `pagefly ${String(Math.round(files[pair.pagefly].length / 1024)).padStart(3)}KB`,
    );
  }

  console.log(`\nwrote ${written.length * 2} files to public/showcase/pages/`);
  console.log(`slugs: ${written.join(", ")}`);
  console.log(`\nNow check lib/showcasePages.ts names exactly these slugs.`);
}

main();
